export const REQUEST_SEARCH_ID = "REQUEST_SEARCH_ID";
export const RECEIVE_SEARCH_ID = "RECEIVE_SEARCH_ID";
export const REQUEST_TICKETS = "REQUEST_TICKETS";
export const RECEIVE_TICKETS = "RECEIVE_TICKETS";
export const RECEIVE_ERROR = "RECEIVE_ERROR";
export const IGNORE_ERROR = "IGNORE_ERROR";
export const SORT = "SORT";
export const SORT_CHEAPEST_FIRST = "SORT_CHEAPEST_FIRST";
export const SORT_FASTEST_FIRST = "SORT_FASTEST_FIRST";
export const SORT_OPTIMAL_FIRST = "SORT_OPTIMAL_FIRST";
export const MORE_ITEMS = "MORE_ITEMS";

export const TRANSFERS = "TRANSFERS";
